### ISSUE TITLE
FAILED: _deps/s2-build/libs2.0.10.0.so 

### ISSUE THREAD

**Issue by tanglinyan** [sulewicz/redis-s2geo#1]
[117/126] Linking CXX shared library _deps/s2-build/libs2.0.10.0.so
FAILED: _deps/s2-build/libs2.0.10.0.so 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -DDEBUG -v -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -dynamiclib -Wl,-headerpad_max_install_names -current_version 0.10.0 -o _deps/s2-build/libs2.0.10.0.so -install_name @rpath/libs2.0.so _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2cell_id_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2point_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_string_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/id_set_lexicon.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/mutable_s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/r2rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1angle.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1chord_angle.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1interval.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2boolean_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2buffer_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builder_graph.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_closed_set_normalizer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_find_polygon_degeneracies.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_get_snapped_winding_delta.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_lax_polygon_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_lax_polyline_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2point_vector_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polygon_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polyline_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polyline_vector_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_snap_functions.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cap.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_id.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_union.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2centroids.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_cell_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_point_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2contains_vertex_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2convex_hull_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2coords.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2crossing_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2debug.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2earth.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_clipping.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_crosser.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_crossings.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_distances.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_tessellator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2furthest_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng_rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng_rect_bounder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_loop_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_polygon_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_polyline_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2loop.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2loop_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2memory_tracker.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2metrics.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2max_distance_targets.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2min_distance_targets.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2padded_cell.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2point_compression.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2point_region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2pointutil.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polygon.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_alignment.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_simplifier.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2predicates.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2projections.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2r2rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_term_indexer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_coverer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_intersection.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_union.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index_buffered_region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_build_polygon_boundaries.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_coding.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_contains_brute_force.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_conversion.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_edge_iterator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_get_reference_point.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_range_iterator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_visit_crossing_edge_pairs.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2text_format.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2wedge_relations.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2winding_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/strings/serialize.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/bits/bit-interleave.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/bits/bits.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/coding/coder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/coding/varint.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/math/mathutil.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/units/length-units.cc.o  /usr/local/opt/openssl@3/lib/libssl.dylib  /usr/local/opt/openssl@3/lib/libcrypto.dylib  /usr/local/abseil/lib/libabsl_base.a  /usr/local/abseil/lib/libabsl_hash.a  /usr/local/abseil/lib/libabsl_int128.a  /usr/local/abseil/lib/libabsl_log_severity.a  /usr/local/abseil/lib/libabsl_strings.a  /usr/local/abseil/lib/libabsl_hash.a  /usr/local/abseil/lib/libabsl_city.a  /usr/local/abseil/lib/libabsl_bad_variant_access.a  /usr/local/abseil/lib/libabsl_low_level_hash.a  /usr/local/abseil/lib/libabsl_cord.a  /usr/local/abseil/lib/libabsl_cordz_info.a  /usr/local/abseil/lib/libabsl_cord_internal.a  /usr/local/abseil/lib/libabsl_cordz_functions.a  /usr/local/abseil/lib/libabsl_cordz_handle.a  /usr/local/abseil/lib/libabsl_raw_hash_set.a  /usr/local/abseil/lib/libabsl_bad_optional_access.a  /usr/local/abseil/lib/libabsl_hashtablez_sampler.a  /usr/local/abseil/lib/libabsl_exponential_biased.a  /usr/local/abseil/lib/libabsl_synchronization.a  /usr/local/abseil/lib/libabsl_stacktrace.a  /usr/local/abseil/lib/libabsl_graphcycles_internal.a  /usr/local/abseil/lib/libabsl_symbolize.a  /usr/local/abseil/lib/libabsl_debugging_internal.a  /usr/local/abseil/lib/libabsl_malloc_internal.a  /usr/local/abseil/lib/libabsl_demangle_internal.a  /usr/local/abseil/lib/libabsl_time.a  /usr/local/abseil/lib/libabsl_civil_time.a  /usr/local/abseil/lib/libabsl_time_zone.a  -framework  CoreFoundation  /usr/local/abseil/lib/libabsl_str_format_internal.a  /usr/local/abseil/lib/libabsl_strings.a  /usr/local/abseil/lib/libabsl_int128.a  /usr/local/abseil/lib/libabsl_throw_delegate.a  /usr/local/abseil/lib/libabsl_strings_internal.a  /usr/local/abseil/lib/libabsl_base.a  /usr/local/abseil/lib/libabsl_spinlock_wait.a  /usr/local/abseil/lib/libabsl_raw_logging_internal.a  /usr/local/abseil/lib/libabsl_log_severity.a && :
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -dylib -dylib_current_version 0.10.0 -arch x86_64 -dylib_install_name @rpath/libs2.0.so -platform_version macos 12.0.0 12.1 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -o _deps/s2-build/libs2.0.10.0.so -headerpad_max_install_names _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2cell_id_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2point_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/encoded_string_vector.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/id_set_lexicon.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/mutable_s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/r2rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1angle.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1chord_angle.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s1interval.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2boolean_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2buffer_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builder_graph.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_closed_set_normalizer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_find_polygon_degeneracies.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_get_snapped_winding_delta.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_lax_polygon_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_lax_polyline_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2point_vector_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polygon_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polyline_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_s2polyline_vector_layer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2builderutil_snap_functions.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cap.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_id.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2cell_union.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2centroids.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_cell_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2closest_point_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2contains_vertex_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2convex_hull_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2coords.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2crossing_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2debug.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2earth.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_clipping.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_crosser.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_crossings.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_distances.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2edge_tessellator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2furthest_edge_query.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng_rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2latlng_rect_bounder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_loop_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_polygon_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2lax_polyline_shape.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2loop.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2loop_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2memory_tracker.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2metrics.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2max_distance_targets.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2min_distance_targets.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2padded_cell.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2point_compression.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2point_region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2pointutil.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polygon.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_alignment.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2polyline_simplifier.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2predicates.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2projections.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2r2rect.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_term_indexer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_coverer.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_intersection.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2region_union.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index_buffered_region.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_index_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shape_measures.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_build_polygon_boundaries.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_coding.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_contains_brute_force.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_conversion.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_edge_iterator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_get_reference_point.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_range_iterator.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2shapeutil_visit_crossing_edge_pairs.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2text_format.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2wedge_relations.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/s2winding_operation.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/strings/serialize.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/bits/bit-interleave.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/bits/bits.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/coding/coder.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/coding/varint.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/math/mathutil.cc.o _deps/s2-build/CMakeFiles/s2.dir/src/s2/util/units/length-units.cc.o /usr/local/opt/openssl@3/lib/libssl.dylib /usr/local/opt/openssl@3/lib/libcrypto.dylib /usr/local/abseil/lib/libabsl_base.a /usr/local/abseil/lib/libabsl_hash.a /usr/local/abseil/lib/libabsl_int128.a /usr/local/abseil/lib/libabsl_log_severity.a /usr/local/abseil/lib/libabsl_strings.a /usr/local/abseil/lib/libabsl_hash.a /usr/local/abseil/lib/libabsl_city.a /usr/local/abseil/lib/libabsl_bad_variant_access.a /usr/local/abseil/lib/libabsl_low_level_hash.a /usr/local/abseil/lib/libabsl_cord.a /usr/local/abseil/lib/libabsl_cordz_info.a /usr/local/abseil/lib/libabsl_cord_internal.a /usr/local/abseil/lib/libabsl_cordz_functions.a /usr/local/abseil/lib/libabsl_cordz_handle.a /usr/local/abseil/lib/libabsl_raw_hash_set.a /usr/local/abseil/lib/libabsl_bad_optional_access.a /usr/local/abseil/lib/libabsl_hashtablez_sampler.a /usr/local/abseil/lib/libabsl_exponential_biased.a /usr/local/abseil/lib/libabsl_synchronization.a /usr/local/abseil/lib/libabsl_stacktrace.a /usr/local/abseil/lib/libabsl_graphcycles_internal.a /usr/local/abseil/lib/libabsl_symbolize.a /usr/local/abseil/lib/libabsl_debugging_internal.a /usr/local/abseil/lib/libabsl_malloc_internal.a /usr/local/abseil/lib/libabsl_demangle_internal.a /usr/local/abseil/lib/libabsl_time.a /usr/local/abseil/lib/libabsl_civil_time.a /usr/local/abseil/lib/libabsl_time_zone.a -framework CoreFoundation /usr/local/abseil/lib/libabsl_str_format_internal.a /usr/local/abseil/lib/libabsl_strings.a /usr/local/abseil/lib/libabsl_int128.a /usr/local/abseil/lib/libabsl_throw_delegate.a /usr/local/abseil/lib/libabsl_strings_internal.a /usr/local/abseil/lib/libabsl_base.a /usr/local/abseil/lib/libabsl_spinlock_wait.a /usr/local/abseil/lib/libabsl_raw_logging_internal.a /usr/local/abseil/lib/libabsl_log_severity.a -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "absl::strings_internal::CatPieces(std::initializer_list<absl::string_view>)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > absl::StrCat<>(absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&) in s2shapeutil_edge_iterator.cc.o
  "absl::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, absl::string_view)", referenced from:
      s2textformat::ParseLatLngsOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::ParsePointsOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::MakePointOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::MakeLatLngOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::MakeLatLngRectOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::MakeCellIdOrDie(absl::string_view) in s2text_format.cc.o
      s2textformat::MakeCellUnionOrDie(absl::string_view) in s2text_format.cc.o
      ...
  "absl::ByChar::Find(absl::string_view, unsigned long) const", referenced from:
      absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::SkipWhitespace, absl::string_view> >::operator++() in s2text_format.cc.o
      absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::AllowEmpty, absl::string_view> >::operator++() in s2text_format.cc.o
      absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::AllowEmpty, absl::string_view> >::operator++() in serialize.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sulewicz** [comment]
Hello! Thank you for your report, we will tackle the linking problem in https://github.com/sulewicz/redis-s2geo/issues/2.
